// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import EditorController from "./editor_controller"
application.register("editor", EditorController)

import GameObserverController from "./game_observer_controller"
application.register("game-observer", GameObserverController)

import LessonController from "./lesson_controller"
application.register("lesson", LessonController)

import LobbyController from "./lobby_controller"
application.register("lobby", LobbyController)

import NavigationNestedMenuController from "./navigation_nested_menu_controller"
application.register("navigation-nested-menu", NavigationNestedMenuController)

import PanoramaController from "./panorama_controller"
application.register("panorama", PanoramaController)

import YoutubePlayerController from "./youtube_player_controller"
application.register("youtube-player", YoutubePlayerController)
