// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
import NavigationNestedMenuController from "./navigation_nested_menu_controller"
import PanoramaController from "./panorama_controller"
import LobbyController from "./lobby_controller"
application.register("hello", HelloController)
application.register("navigation", NavigationNestedMenuController)
application.register("panorama", PanoramaController)
application.register("lobby", LobbyController)
