default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: storage/production.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3

production:
  primary:
    <<: *default
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    adapter: postgresql
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate